
jobs:
- job:
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    displayName: Compilacion


  #- task: SonarCloudPrepare@1
  #  inputs:
  #    SonarCloud: 'SonarCloud'
  #    organization: 'devopsfundations-joel-mora'
  #    projectKey: 'DevOpsFundations-Joel-mora_springpet-clinic'
  #    projectName: 'springpet-clinic'
  #  displayName: 'Sonar Cloud Prerare'

  #- task: Gradle@3
  #  inputs:
  #    gradleWrapperFile: 'gradlew'
  #    tasks: 'sonarqube'
  #    publishJUnitResults: false
  #    javaHomeOption: 'JDKVersion'
  #    sonarQubeRunAnalysis: true
  #    sqGradlePluginVersionChoice: 'specify'
  #    sonarQubeGradlePluginVersion: '3.5.0.2730'
  #    spotBugsAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'joeljmora/petclinic'
      command: 'build'
      Dockerfile: '**/Dockerfile'


  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'joeljmora/petclinic'
      command: 'push'
  
- job:
  pool: 'default'
  steps: 
  - task: Kubernetes@1
    inputs:
      connectionType: 'None'
      command: 'create'
      useConfigurationFile: true
      configuration: './kubernetes/deployment-app.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'