pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Compilacion
#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'SonarCloud'
#    organization: 'devopsfundations-joel-mora'
#    projectKey: 'DevOpsFundations-Joel-mora_springpet-clinic'
#    projectName: 'springpet-clinic'
#  displayName: 'Sonar Cloud Prerare'

#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'sonarqube'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: true
#    sqGradlePluginVersionChoice: 'specify'
#    sonarQubeGradlePluginVersion: '3.5.0.2730'
#    spotBugsAnalysis: false